name: Build Localized Images

concurrency:
  group: gh-pages-update-${{ github.repository }}
  cancel-in-progress: false

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * *'  # 毎日チェック
  workflow_dispatch:
    inputs:
      force_build:
        description: 'Force build regardless of upstream changes'
        default: false
        type: boolean

env:
  DST_REGISTRY: ghcr.io
  DST_USER: musclepr

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    strategy:
      matrix:
        include:
          - name: minecraft-server:latest
            src: itzg
            artifact: minecraft-server-latest
          - name: minecraft-server:java17
            src: itzg
            artifact: minecraft-server-java17
          - name: mc-proxy:latest
            src: itzg
            artifact: mc-proxy-latest
          - name: mc-backup:latest
            src: itzg
            artifact: mc-backup-latest

    steps:
    - uses: actions/checkout@v4

    - name: Check if build needed (gh-pages digests)
      id: check
      run: |
        SRC_IMG="${{ matrix.src }}/${{ matrix.name }}"
        DIGESTS_URL="https://musclepr.github.io/localized-images/digests.json"
        # Force build or push event
        if [ "${{ github.event.inputs.force_build }}" = "true" ] || [ "${{ github.event_name }}" = "push" ]; then
          echo "needs_build=true" >> $GITHUB_OUTPUT
          echo "Reason: Force build or push event"
          exit 0
        fi
        # Get previous digest from gh-pages
        PREV_DIGEST=$(curl -s "$DIGESTS_URL" | jq -r --arg key "$SRC_IMG" '.[$key] // empty')
        # Get upstream digest
        UP_DIGEST=$(docker manifest inspect $SRC_IMG 2>/dev/null | jq -r '.manifests[0].digest // .digest' || echo "")
        if [ "$PREV_DIGEST" = "$UP_DIGEST" ] && [ -n "$PREV_DIGEST" ]; then
          echo "needs_build=false" >> $GITHUB_OUTPUT
          echo "上流に変更なし。ビルド不要。"
        else
          echo "needs_build=true" >> $GITHUB_OUTPUT
          echo "上流に変更あり。ビルド必要。"
        fi

    - name: Set up Docker Buildx
      if: steps.check.outputs.needs_build == 'true'
      uses: docker/setup-buildx-action@v3

    - name: Login to GHCR
      if: steps.check.outputs.needs_build == 'true'
      uses: docker/login-action@v3
      with:
        registry: ${{ env.DST_REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push
      if: steps.check.outputs.needs_build == 'true'
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        build-args: |
          IMAGE=${{ matrix.src }}/${{ matrix.name }}
        tags: ${{ env.DST_REGISTRY }}/${{ env.DST_USER }}/${{ matrix.name }}
        labels: |
          org.opencontainers.image.source=${{ github.server_url }}/${{ github.repository }}
          org.opencontainers.image.revision=${{ github.sha }}

    - name: Collect digest data
      if: steps.check.outputs.needs_build == 'true'
      run: |
        SRC_IMG="${{ matrix.src }}/${{ matrix.name }}"
        UP_DIGEST=$(docker manifest inspect "$SRC_IMG" 2>/dev/null | jq -r '.manifests[0].digest // .digest' || echo "")
        mkdir -p digest
        echo '{}' > digest/digest.json
        jq --arg key "$SRC_IMG" --arg val "$UP_DIGEST" '.[$key]=$val' digest/digest.json > digest/digest.tmp && mv digest/digest.tmp digest/digest.json

    - name: Upload digest artifact
      if: steps.check.outputs.needs_build == 'true'
      uses: actions/upload-artifact@v4
      with:
        name: digest-${{ matrix.src }}-${{ matrix.artifact }}
        path: digest/digest.json
        if-no-files-found: error

  update-digests:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download digest artifacts
        continue-on-error: true
        uses: actions/download-artifact@v4
        with:
          pattern: digest-*
          path: digests
          merge-multiple: true

      - name: Merge digest snippets
        id: merge
        run: |
          if [ ! -d digests ]; then
            echo "has_updates=false" >> "$GITHUB_OUTPUT"
            exit 0
          fi
          shopt -s nullglob globstar
          files=(digests/**/digest.json)
          if [ ${#files[@]} -eq 0 ]; then
            echo "has_updates=false" >> "$GITHUB_OUTPUT"
            exit 0
          fi
          jq -s 'reduce .[] as $item ({}; . * ($item | with_entries(select(.value != ""))))' "${files[@]}" > merged-digests.json
          if [ ! -s merged-digests.json ] || [ "$(jq 'length' merged-digests.json)" -eq 0 ]; then
            echo "has_updates=false" >> "$GITHUB_OUTPUT"
            exit 0
          fi
          echo "has_updates=true" >> "$GITHUB_OUTPUT"

      - name: Update digests.json on gh-pages
        if: steps.merge.outputs.has_updates == 'true'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "github-actions"
          git clone --branch gh-pages --depth 1 "https://github.com/${{ github.repository }}.git" gh-pages
          cd gh-pages
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
          if [ ! -f digests.json ]; then echo "{}" > digests.json; fi
          jq -s 'reduce .[] as $item ({}; . * $item)' digests.json ../merged-digests.json > digests.json.tmp && mv digests.json.tmp digests.json
          git add digests.json
          if git diff --cached --quiet; then
            echo "No changes to commit."
            exit 0
          fi
          IMAGE_LIST=$(jq -r 'keys | join(", ")' ../merged-digests.json)
          if [ -z "$IMAGE_LIST" ]; then
            IMAGE_LIST="更新対象なし"
          fi
          git commit -m "ダイジェスト更新: $IMAGE_LIST"
          git pull --rebase origin gh-pages
          git push origin gh-pages
